version: '3'

services:
  db:
    image: postgres:15.3
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"

volumes:
  data: {}